### PR TITLE
Hover on descriptions for cache parameters

### PR DESCRIPTION
**Pull request by wthompson40**
Hover on descriptions for cache parameters

### CODE REVIEW

**Review by jbonzo — CHANGES_REQUESTED** [review]
A lot of the boxes texts are blocked off and I can't get cacheSize to work

**Comment by wthompson40** [comment]
I don't quite know what you mean by "blocked off".  The initial size of the cache input component is too small, so making it a little bigger helps with readability of these popups.  Initially I had a popup for cache size, but it proved difficult as it was covered by the div containing the choice of policy and block size.

**Comment by jbonzo** [comment]
image

**Comment by jbonzo** [comment]
texts leaks out of text box it appears

**Comment by wthompson40** [comment]
cache

When I drag the cache input component far enough out, this is what it looks like for me.

**Review by jbonzo — APPROVED** [review]
Not perfect but better.

**Pull request merged**
