### PR TITLE
Issue 82

### PR DESCRIPTION
**Pull request by wthompson40**

### CODE REVIEW

**Comment by jbonzo** [comment]
Not sure if you addressed this already but the X close button doesn't work.
Also on the top left is says `modal-00`. Not sure what that's supposed to be.

**Comment by wthompson40** [comment]
Yeah, the button does not work to close it.  Clicking anywhere off the modal element will close it though.  And in the top left there is a number XX, this represents which associativity column it is in followed by which row it is.  We need an individual modal element per table element as the modal will be the breakdown of the given tag (as a block).

**Comment by jbonzo** [comment]
ok. I think I rather have someone else also take a look at this to see if it meets the vision discussed the other day. @ryan-berst @kevinsrose @emestanza3

**Comment by kevinsrose** [comment]
This looks awesome! Only small issue I noticed is that the X doesn't close the window like Ricky already mentioned.

**Comment by wthompson40** [comment]
I spent a while trying to get that button to work, really not sure what the problem is.  You can close the modal element by clicking on the background.

**Comment by wthompson40** [comment]
Alright, fixed the close button.

**Review by kevinsrose — APPROVED** [review]

**Pull request merged**
