### PR TITLE
Issue 118

### PR DESCRIPTION
**Pull request by kevinsrose**
The control flow buttons are now functional, highlighting the correct row of the memory access queue based on the current instruction. Playing the simulation calls the stepForward function every time interval that is set by the speed slider.

### CODE REVIEW

**Comment by kevinsrose** [comment]
Also, the time intervals for playing the simulation currently range from 1s when slider=1 and 0.2s when slider=5. This can easily be changed if necessary.

**Comment by ryan-berst** [comment]
Beautiful!

**Comment by ryan-berst** [comment]
The table doesn't appear if the first button I press is "step forward". Are we planning on disabling these buttons?

**Comment by kevinsrose** [comment]
Yes, currently the MAQ table only appears and the simulation only starts when the play button is clicked. I'll go ahead and update this PR to disable the buttons until the simulation is started.

**Review by ryan-berst — APPROVED** [review]
Hands-on, looks good

**Pull request merged**
