### PR TITLE
Cache details

### PR DESCRIPTION
**Pull request by wthompson40**
Changed the details of the cache details page, include tag, index, and offset.

TODO: Ensure when a tracefile is uploaded and simulation is started, that cache level details are correctly populated.

### CODE REVIEW

**Review by jbonzo — COMMENTED** [review]
Tag seems to be in the middle-ish part of the page. is anything supposed to go in that far left side if the header par?

**Review by jbonzo — COMMENTED** [review]
also offset is very far right. would that look weird when values are populated in that column?

**Comment by kevinsrose** [comment]
The way I have them ordered in the memory access queue is:
Address | Tag | Index | Offset

**Comment by wthompson40** [comment]
Fixed those problems, looking for an approval.

**Review by jbonzo — APPROVED** [review]

**Pull request merged**
